#import "@local/bootlin:0.1.0": *

#import "@local/bootlin-yocto:0.1.0": *

#import "@local/bootlin-utils:0.1.0": *

#import "/typst/local/themeBootlin.typ": *

#import "/typst/local/common.typ": *

#show: bootlin-theme.with( aspect-ratio: "16-9",
config-common(handout: "handout" in sys.inputs and sys.inputs.handout
== "1", ))

#show raw.where(block: true): set block(fill: luma(240), inset: 1em,
radius: 0.5em, width: 100%)

#show raw.where(block: true): set text(size: 11pt)

#show raw.where(block: false): r => text(fill: color-link)[#r]

#show raw.where(lang: "c", block: true): set block(fill: luma(240),
inset: 0.4em, radius: 0.5em, width: 95%, breakable: true, above: 12pt,
below: 12pt)

#show raw.where(lang: "c", block: true): set text(11pt)

#show raw.where(lang: "console", block: true):set block(fill:
luma(240), inset: 0.4em, radius: 0.5em, width: 95%, breakable: true,
above: 6pt)

#show raw.where(lang:"console", block: true): set text(12pt)

===  Initramfs for boot time reduction Create the smallest initramfs
possible, just enough to start the critical application and then switch
to the final root filesystem with `switch_root`:

- Use a light C library reduced to the minimum, #emph[uClibc] or
  #emph[Musl] if you are not yet using it for your root filesystem

- Reduce BusyBox to the strict minimum. You could even do without it and
  implement `/init` in C.

- Use statically linked applications (less CPU overhead, less libraries
  to load, smaller initramfs if no libraries at all),
  `BR2_STATIC_LIBS` in Buildroot.

===  Statically linked executables: licensing constraints

- Statically linked executables are very useful to reduce size
  (especially in small initramfs), and require less work to start.

- However, the LGPL license in the uClibc and glibc libraries requires
  to leave the user the ability to relink the executable with a modified
  version of the library.

- Solution to keep static binaries:

  - Either provide the executable source code (even proprietary),
    allowing to recompile it with a modified version of the library.
    That’s what you do when you ship a static BusyBox.

  - Or also provide a dynamically linked version of the executable (in a
    separate way), allowing to use another library version.

  - Easiest solution: build your static executables with the `musl`
    library (MIT license: no trouble)

- References: 
  #link("https://gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic")[https://gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic]
  
  #link("https://gnu.org/copyleft/lesser.html#section4")[https://gnu.org/copyleft/lesser.html#section4]

===  Do not compress your initramfs

- If you ship your initramfs inside a compressed kernel image, don’t
  compress it 
  (enable #kconfig("CONFIG_INITRAMFS_COMPRESSION_NONE")).

- Otherwise, by default, your initramfs data will be compressed twice,
  and the kernel will be bigger and will take a little more time to load
  and uncompress.

- Example on Linux 5.1 with a 1.60 MB initramfs (tar archive size) on
  Beagle Bone Black: this allowed to reduce the kernel size from 4.94 MB
  to 4.74 MB (-200 KB) and save about 170 ms of boot time.

#setuplabframe([Filesystem optimizations],[

- Comparing the boot time performance of various filesystems

- Tests with initramfs booting too

])

===  Filesystem optimizations - Results Results on BeagleBone Black,
Linux 5.11

#align(center)[#table(
  columns: 6,
  align: (col, row) => (left,center,center,center,center,center,).at(col),
  inset: 6pt,
  [FS image size],
  [],
  [],
  [],
  [],
  [],
  [image size],
  [],
  [],
  [],
  [],
  [],
  [diff],
  [Time to init],
  [],
  [],
  [],
  [],
  [boot time],
  [],
  [],
  [],
  [],
  [],
  [exec time],
  [],
  [],
  [],
  [],
  [],
  [ext2 (rev1) only],
  [62,914,560],
  [+19,544],
  [8.489s],
  [9.704s],
  [0.498s],
  [ext4 only],
  [62,914,560],
  [+241,472],
  [8.645s],
  [9.862s],
  [0.484s],
  [btrfs],
  [114,294,784],
  [+546,376],
  [11.789s],
  [12.918s],
  [0.487s],
  [f2fs],
  [104,857,600],
  [+167,640],
  [8.670s],
  [9.803s],
  [0.488s],
  [squashfs with lzo],
  [724,992],
  [+19,016],
  [8.500s],
  [9.721s],
  [0.436s],
  [erofs without compression],
  [1,196,032],
  [+28,072],
  [8.510s],
  [9.795s],
  [0.491s],
  [initramfs],
  [N/A],
  [+169,552],
  [8.399s],
  [9.660s],
  [0.455s],
)
]

Note: `zImage` kernel compressed with LZMA (best but slowest
compressor), with a 1.162 MB filesystem (size of the tar archive
generated by Buildroot).
